---
- name: Playbook to create LV, Filesystem and Mount it
  hosts: k8s_servers
  remote_user: root
  become: yes
  become_method: sudo
  #gather_facts: no
  vars:
    raw_disks: /dev/vdb # /dev/vdb,dev/vdc
    vg_name: vg10
    lv_name: container_data
    lv_size: +100%FREE #80%VG, 200G
    fs_type: xfs
    mount_path: /var/lib/longhorn
  tasks:
    - name: Get LV UUID
      ansible.builtin.command: lsblk /dev/{{ vg_name }}/{{ lv_name }} -no UUID
      register: lv_uuid
      ignore_errors: true

    - name: Unmount created filesystem
      ansible.posix.mount:
        path: "{{ mount_path }}"
        src: UUID={{ lv_uuid.stdout }}
        state: unmounted
        fstype: "{{ fs_type }}"

    - name: Delete filesystem on LV
      community.general.filesystem:
        fstype: "{{ fs_type }}"
        resizefs: true
        dev:  /dev/{{ vg_name }}/{{ lv_name }}
        state: absent

    - name: Delete Logical Volume for data persistence
      community.general.lvol:
        vg: "{{ vg_name }}"
        lv: "{{ lv_name }}"
        size: "{{ lv_size }}"
        state: absent
        force: true

    - name: Delete the volume group
      community.general.lvg:
        vg: "{{ vg_name }}"
        pvs: "{{ raw_disks }}"
        state: absent
